name = Simple pik
description = A simple pik 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = simple_pik-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer_first]   = Footer first
regions[footer_second]  = Footer second

; Stylesheets
stylesheets[all][] = css/layouts/simple_pik/simple_pik.layout.css
